### ISSUE TITLE
is it possible to show tabs like chrome?

### ISSUE THREAD

**Issue by thasneemp** [michael-rapp/ChromeLikeTabSwitcher#10]

**Comment by thasneemp** [comment]
its showing one tab full screen how it will be work with tablet screen

**Comment by michael-rapp** [comment]
This is planned for the upcoming 1.0.0 release. I am still working on it. It is far more complex as expected. There is a preview available on the branch 1.0.0-development. But do not expect too much. It's just an early prototype and many things don't work yet.
