### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by rainboy93** [michael-rapp/ChromeLikeTabSwitcher#12]
Hi,
Thank you for amazing coding!
Can you please show me the starting point for me in order to modify the tabs layout? For example i want it be horizontal and not stacked.
Thank in advance!

**Comment by michael-rapp** [comment]
There is no possibility to easily change the way tabs are layouted and moved when dragging. It is not planned to provide a feature like this in the future.

To implement a custom layout basically everything within the package [de.mrapp.android.tabswitcher.layout.phone](https://github.com/michael-rapp/ChromeLikeTabSwitcher/tree/master/library/src/main/java/de/mrapp/android/tabswitcher/layout/phone) has to be reimplemented. Some parts of the code could probably be reused, but nevertheless this would require a lot of effort.

**Comment by rainboy93** [comment]
Thank you for suggesting!
