### ISSUE TITLE
Example crashes on tablets

### ISSUE THREAD

**Issue by dakdroid** [michael-rapp/ChromeLikeTabSwitcher#13]
Is this expected?
Emulator Nexus 9 API 26

Could you add a workaround for this? The phone layout on tablets would be ok.

**Comment by michael-rapp** [comment]
No it is not expected. It should show the phone layout since the tablet layout is not available yet.

**Comment by michael-rapp** [comment]
Fixed in version 0.2.9. But do not expect the best performance on tablets. The phone layout is not meant to be used on large screen.
