### ISSUE TITLE
ChromeLikeTabSwitcher

### ISSUE THREAD

**Issue by ayushnitra** [michael-rapp/ChromeLikeTabSwitcher#30]
Sir,
 I want to perform click event in CardView in Tab_text_view layout , How can We perform this .
I am using your Tab 1 Layout and want to perform click on cardView.

![tadd](https://user-images.githubusercontent.com/68224796/87496294-e80ca100-c670-11ea-8f44-57811f554c55.PNG)
![tabs](https://user-images.githubusercontent.com/68224796/87496302-eb079180-c670-11ea-9f0c-36a28d3e1599.png)

**Comment by michael-rapp** [comment]
Just as I wrote in #28, override the `onShowTab`-method of the class [`TabSwitcherDecorator`](https://github.com/michael-rapp/ChromeLikeTabSwitcher/blob/master/library/src/main/java/de/mrapp/android/tabswitcher/TabSwitcherDecorator.java) and do something like the following:
```java
CardView cardView = findViewById(R.id.card_google);
cardView.setOnClickListener(...);
```

**Comment by ayushnitra** [comment]
thanks sir, but It gives error and when I am launching the app It is crashing, and giving the error, I did not change anything in your program I just use a button and try to  its click message but app is crashing Please sir give proper solution
![err1](https://user-images.githubusercontent.com/68224796/87842109-8c882080-c8c7-11ea-9edc-a4a9456e1b2f.PNG)
![err2](https://user-images.githubusercontent.com/68224796/87842114-93af2e80-c8c7-11ea-9e8a-c19446dc4a16.PNG)

**Comment by michael-rapp** [comment]
The general structure of the code should be correct, but the `findViewById`-method does not find the button. I am sorry, but this is something I cannot help you with. Without having the whole code available and being able to run it, it is almost impossible to figure this out. There might be a typo somewhere or an import that refers to the wrong file...I am afraid you have to figure this out on your own by carefully looking at the code and debugging it.

**Comment by ayushnitra** [comment]
OK sir, thanks u so much, I will do it .
In your ChromeLikeTabSwitcher complete code  , Can You use one of the Tab layout(eg. tab_text_view.xml,  tab_list_view.xml, tab_edit_text.xml) and show me how to apply setOnClickListerner for click event;
Please Sir show me how to perform click event on your tab layout.
All the Tab layout of your program can view not apply click event Please sir apply click event.
Sir Its highly request 🙏🙏🙏

Link of your code-  https://github.com/michael-rapp/ChromeLikeTabSwitcher/tree/master/example/src/main/res/layout

Screenshot where request to apply setonclickListener on anybutton
![t333](https://user-images.githubusercontent.com/68224796/87865661-b90a6e00-c995-11ea-848c-c97ef9b5f1a2.PNG)
