### ISSUE TITLE
How to restore the state of the tab when returning from the activity

### ISSUE THREAD

**Issue by AbhayJangde** [michael-rapp/ChromeLikeTabSwitcher#8]
I have a tab in which the webview is attached to the tab and ''google.com" is launched. I wanted to restore the state of the tab which is shown earlier when navigating back from an another activity. What happens is now the url is reloaded in the webview, whenever I'm coming back to the MainActivity.

**Comment by michael-rapp** [comment]
As far as I remember, activities are not restored by default when navigating back, but they are recreated.  Try setting the attribute `android:launchMode="singleTop"` for your `MainActivity` in the `Manifest.xml` to force reuse of the activity. Please tell me, if this solves your problem.

**Comment by michael-rapp** [comment]
I will now close this issue. If you still encounter problems, feel free to reopen it and provide more information.

**Comment by yeahia2508** [comment]
this not sloved my problem @michael-rapp
