### ISSUE TITLE
Getting NullPointerException when inflating the TabSwitcher Menu

### ISSUE THREAD

**Issue by joshy24** [michael-rapp/ChromeLikeTabSwitcher#9]
I am attempting to inflate the tabSwitcher menu with the following code

      Menu menu = tabSwitcher.getToolbarMenu();
        TabSwitcher.setupWithMenu(tabSwitcher, menu, new View.OnClickListener() {
            @Override
            public void onClick(View v) {

            }
        });

And i have set the menu on the tabswitcher in the layout file like this

    <de.mrapp.android.tabswitcher.TabSwitcher
        android:id="@+id/tab_switcher"
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:custom="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/tab_switcher_background_color"
        custom:layoutPolicy="auto"
        custom:tabIcon="@drawable/ic_file"
        custom:tabBackgroundColor="@color/tab_background_color"
        custom:tabTitleTextColor="@color/tab_title_text_color"
        custom:tabCloseButtonIcon="@drawable/ic_close"
        custom:toolbarTitle="@string/tab_switcher_toolbar_title"
        custom:toolbarMenu="@menu/tab_switcher_toolbar_menu"
        custom:toolbarNavigationIcon="@drawable/ic_add_box"/>

But i get a nullpointer exception at runtime which says that the menu gotten from tabSwitcher.getToolbarMenu(); is null

This is the tab_switcher_toolbar_menu

<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <item
        android:id="@+id/toggle_tab_switcher_menu_item"
        android:title="New Tab"
        app:actionLayout="@layout/tab_switcher_menu_item"
        app:showAsAction="ifRoom" />

</menu>

**Comment by michael-rapp** [comment]
To track down your issue please try the following things:

- Call `tabSwitcher.showToolbars(true);` before calling `getToolbarMenu()` and see if it solves your problem.
- If you remove the line of code that causes the `NullPointerException`, can you see the menu item?
- Call `tabSwitcher.getToolbars()' and check, if a Toolbar is contained by the returned array. There should be one.
- Please tell me, where the piece of code you've posted is executed? Inside the activity's `onCreate`-method?

**Comment by joshy24** [comment]
I tried adding the tabSwitcher.showToolbars(true); before calling getToolbarMenu();

This is my onCreate method  

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ButterKnife.bind(this);

        tabSwitcher.setDecorator(new TabDecorator());


        tabSwitcher.showToolbars(true);

        Menu menu = tabSwitcher.getToolbarMenu();
        TabSwitcher.setupWithMenu(tabSwitcher, menu, new View.OnClickListener() {
            @Override
            public void onClick(View v) {

            }
        });


        Tab tab1 = new Tab("Title");
        tab1.setCloseable(true);
        tab1.setIcon(R.drawable.ic_file);
        tab1.setBackgroundColor(ContextCompat.getColor(this, R.color.tab_background_color));
        tab1.setTitleTextColor(ContextCompat.getColor(this, R.color.tab_title_text_color));
        tab1.setParameters(new Bundle());
        tab1.addCallback(new Tab.Callback() {
            @Override
            public void onTitleChanged(@NonNull Tab tab) {

            }

            @Override
            public void onIconChanged(@NonNull Tab tab) {

            }

            @Override
            public void onCloseableChanged(@NonNull Tab tab) {

            }

            @Override
            public void onCloseButtonIconChanged(@NonNull Tab tab) {

            }

            @Override
            public void onBackgroundColorChanged(@NonNull Tab tab) {

            }

            @Override
            public void onTitleTextColorChanged(@NonNull Tab tab) {

            } /* ... */ });
        tabSwitcher.addTab(tab1);

        tabSwitcher.showSwitcher();

**Comment by michael-rapp** [comment]
Thanks. I will try to reproduce the issue using your code.

**Comment by michael-rapp** [comment]
I was able to reproduce the error using your code. The solution is to replace the following lines of code

```java
Menu menu = tabSwitcher.getToolbarMenu();
TabSwitcher.setupWithMenu(tabSwitcher, menu, new View.OnClickListener() {
        
    @Override
    public void onClick(View v) {

    }
});
```
with the following
```java
tabSwitcher.getViewTreeObserver().addOnGlobalLayoutListener(new OnGlobalLayoutListener() {

    @Override
    public void onGlobalLayout() {
        ViewUtil.removeOnGlobalLayoutListener(tabSwitcher.getViewTreeObserver(), this);
        Menu menu = tabSwitcher.getToolbarMenu();
        TabSwitcher.setupWithMenu(tabSwitcher, menu, new View.OnClickListener() {
            
            @Override
            public void onClick(View v) {

            }

        });
    }

});
```
The reason is, that the `TabSwitcher`'s content is not inflated until the view is laid out. This is not happening before the `onCreate`-method ends. By using a `OnGlobalLayoutListener` the menu can be set up as soon as the `TabSwitcher` is laid out. I will add instructions about how to use the `setupWithMenu`-method properly to the readme.

Feel free to reopen this issue, if this solution does not work for you.

**Comment by michael-rapp** [comment]
Since version 0.1.7 you can simply use the following method call for initializing the tab switcher's menu. It will internally take care of the things discussed in https://github.com/michael-rapp/ChromeLikeTabSwitcher/issues/9#issuecomment-353735827.

```java
TabSwitcher.setupWithMenu(tabSwitcher, new View.OnClickListener() {

    @Override
    public void onClick(View v) {

    }
});
```

**Comment by favouritezinash** [comment]
Thanks...sorry for the late response.

It appears that worked...But i cant seem to figure out how to add new tabs to the tabswitcher. 
How do i make the navigation button clickable to add new tabs.

**Comment by michael-rapp** [comment]
I advice you to take a look at the implementation of the example app. In the `onCreate`-method of the class [MainActivity](https://github.com/michael-rapp/ChromeLikeTabSwitcher/blob/master/example/src/main/java/de/mrapp/android/tabswitcher/example/MainActivity.java) you can find the following:
```java
tabSwitcher.setToolbarNavigationIcon(R.drawable.ic_add_box_white_24dp, createAddTabListener());
```
This displays the navigation icon and sets a listener for it. The listener adds a new tab to the tab switcher using an animation when the navigation button is clicked:
```java
private OnClickListener createAddTabListener() {
    return new OnClickListener() {

        @Override
        public void onClick(final View view) {
            int index = tabSwitcher.getCount();
            Animation animation = createRevealAnimation();
            tabSwitcher.addTab(createTab(index), 0, animation);
        }

    };
}
```
